# Print cards for use with combine. See MT2Analysis/limits/SignalScan.
# Reimplementation of cardMaker.C.

import ROOT
import re
from math import sqrt
from sys import argv,exit

# Suppresses warnings about TH1::Sumw2
ROOT.gErrorIgnoreLevel = ROOT.kError

ROOT.gROOT.SetBatch(True)
ROOT.gStyle.SetOptStat(False)
canvas = ROOT.TCanvas()
canvas.SetCanvasSize(700,700)
canvas.SetTicks(2,2)
pads = [canvas]
pads[0].SetLeftMargin(0.14)
pads[0].SetTopMargin(0.12)
pads[0].SetRightMargin(0.12)
pads[0].cd()

ROOT.gStyle.SetLegendBorderSize(0)
tl = ROOT.TLegend(0.55,0.15,0.85,0.30)
tl.SetMargin(0.1)

f_T1 = ROOT.TFile("../T1qqqq_1800_1400.root")
f_T5 = ROOT.TFile("../T5qqqqLLChiChi_2016_baby.root")

h_2to3_1 = f_T1.Get("h_2to3")
h_2to3_5 = f_T5.Get("h_2to3")
h_4to6_1 = f_T1.Get("h_4to6")
h_4to6_5 = f_T5.Get("h_4to6")
h_7plus_1 = f_T1.Get("h_7plus")
h_7plus_5 = f_T5.Get("h_7plus")

h_VL_1 = f_T1.Get("h_VL")
h_L_1 = f_T1.Get("h_L")
h_M_1 = f_T1.Get("h_M")
h_H_1 = f_T1.Get("h_H")
h_UH_1 = f_T1.Get("h_UH")
h_VL_5 = f_T5.Get("h_VL")
h_L_5 = f_T5.Get("h_L")
h_M_5 = f_T5.Get("h_M")
h_H_5 = f_T5.Get("h_H")
h_UH_5 = f_T5.Get("h_UH")

h_VL_2to3_1 = f_T1.Get("h_VL_2to3")
h_L_2to3_1 = f_T1.Get("h_L_2to3")
h_M_2to3_1 = f_T1.Get("h_M_2to3")
h_H_2to3_1 = f_T1.Get("h_H_2to3")
h_UH_2to3_1 = f_T1.Get("h_UH_2to3")
h_VL_4to6_1 = f_T1.Get("h_VL_4to6")
h_L_4to6_1 = f_T1.Get("h_L_4to6")
h_M_4to6_1 = f_T1.Get("h_M_4to6")
h_H_4to6_1 = f_T1.Get("h_H_4to6")
h_UH_4to6_1 = f_T1.Get("h_UH_4to6")
h_VL_7plus_1 = f_T1.Get("h_VL_7plus")
h_L_7plus_1 = f_T1.Get("h_L_7plus")
h_M_7plus_1 = f_T1.Get("h_M_7plus")
h_H_7plus_1 = f_T1.Get("h_H_7plus")
h_UH_7plus_1 = f_T1.Get("h_UH_7plus")

h_VL_2to3_5 = f_T5.Get("h_VL_2to3")
h_L_2to3_5 = f_T5.Get("h_L_2to3")
h_M_2to3_5 = f_T5.Get("h_M_2to3")
h_H_2to3_5 = f_T5.Get("h_H_2to3")
h_UH_2to3_5 = f_T5.Get("h_UH_2to3")
h_VL_4to6_5 = f_T5.Get("h_VL_4to6")
h_L_4to6_5 = f_T5.Get("h_L_4to6")
h_M_4to6_5 = f_T5.Get("h_M_4to6")
h_H_4to6_5 = f_T5.Get("h_H_4to6")
h_UH_4to6_5 = f_T5.Get("h_UH_4to6")
h_VL_7plus_5 = f_T5.Get("h_VL_7plus")
h_L_7plus_5 = f_T5.Get("h_L_7plus")
h_M_7plus_5 = f_T5.Get("h_M_7plus")
h_H_7plus_5 = f_T5.Get("h_H_7plus")
h_UH_7plus_5 = f_T5.Get("h_UH_7plus")

# NJ Ratios
h_2to3_ratio = h_2to3_1.Clone("h_2to3_ratio")
h_2to3_ratio.Divide(h_2to3_5)
h_2to3_ratio.Draw()
canvas.SaveAs("pngs/2to3_ratio.png")
h_4to6_ratio = h_4to6_1.Clone("h_4to6_ratio")
h_4to6_ratio.Divide(h_4to6_5)
h_4to6_ratio.Draw()
canvas.SaveAs("pngs/4to6_ratio.png")
h_7plus_ratio = h_7plus_1.Clone("h_7plus_ratio")
h_7plus_ratio.Divide(h_7plus_5)
h_7plus_ratio.Draw()
canvas.SaveAs("pngs/7plus_ratio.png")

# HT Ratios
h_VL_ratio = h_VL_1.Clone("h_VL_ratio")
h_VL_ratio.Divide(h_VL_5)
h_VL_ratio.Draw()
canvas.SaveAs("pngs/VL_ratio.png")
h_L_ratio = h_L_1.Clone("h_L_ratio")
h_L_ratio.Divide(h_L_5)
h_L_ratio.Draw()
canvas.SaveAs("pngs/L_ratio.png")
h_M_ratio = h_M_1.Clone("h_M_ratio")
h_M_ratio.Divide(h_M_5)
h_M_ratio.Draw()
canvas.SaveAs("pngs/M_ratio.png")
h_H_ratio = h_H_1.Clone("h_H_ratio")
h_H_ratio.Divide(h_H_5)
h_H_ratio.Draw()
canvas.SaveAs("pngs/H_ratio.png")
h_UH_ratio = h_UH_1.Clone("h_UH_ratio")
h_UH_ratio.Divide(h_UH_5)
h_UH_ratio.Draw()
canvas.SaveAs("pngs/UH_ratio.png")

# NJ Overlays
h_2to3_1.SetMaximum(1.1 * max(h_2to3_1.GetMaximum(), h_2to3_5.GetMaximum()) )
h_2to3_1.SetMinimum(0)
h_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_2to3_1,"T1qqqq")
tl.AddEntry(h_2to3_5,"T5qqqq")
h_2to3_1.Draw()
h_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/2to3.png")
tl.Clear()

h_4to6_1.SetMaximum(1.1 * max(h_4to6_1.GetMaximum(), h_4to6_5.GetMaximum()) )
h_4to6_1.SetMinimum(0)
h_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_4to6_1,"T1qqqq")
tl.AddEntry(h_4to6_5,"T5qqqq")
h_4to6_1.Draw()
h_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/4to6.png")
tl.Clear()

h_7plus_1.SetMaximum(1.1 * max(h_7plus_1.GetMaximum(), h_7plus_5.GetMaximum()) )
h_7plus_1.SetMinimum(0)
h_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_7plus_1,"T1qqqq")
tl.AddEntry(h_7plus_5,"T5qqqq")
h_7plus_1.Draw()
h_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/7plus.png")
tl.Clear()

# HT Overlays
h_VL_1.SetMaximum(1.1 * max(h_VL_1.GetMaximum(), h_VL_5.GetMaximum()) )
h_VL_1.SetMinimum(0)
h_VL_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_VL_1,"T1qqqq")
tl.AddEntry(h_VL_5,"T5qqqq")
h_VL_1.Draw()
h_VL_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/VL.png")
tl.Clear()

h_L_1.SetMaximum(1.1 * max(h_L_1.GetMaximum(), h_L_5.GetMaximum()) )
h_L_1.SetMinimum(0)
h_L_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_L_1,"T1qqqq")
tl.AddEntry(h_L_5,"T5qqqq")
h_L_1.Draw()
h_L_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/L.png")
tl.Clear()

h_M_1.SetMaximum(1.1 * max(h_M_1.GetMaximum(), h_M_5.GetMaximum()) )
h_M_1.SetMinimum(0)
h_M_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_M_1,"T1qqqq")
tl.AddEntry(h_M_5,"T5qqqq")
h_M_1.Draw()
h_M_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/M.png")
tl.Clear()

h_H_1.SetMaximum(1.1 * max(h_H_1.GetMaximum(), h_H_5.GetMaximum()) )
h_H_1.SetMinimum(0)
h_H_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_H_1,"T1qqqq")
tl.AddEntry(h_H_5,"T5qqqq")
h_H_1.Draw()
h_H_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/H.png")
tl.Clear()

h_UH_1.SetMaximum(1.1 * max(h_UH_1.GetMaximum(), h_UH_5.GetMaximum()) )
h_UH_1.SetMinimum(0)
h_UH_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_UH_1,"T1qqqq")
tl.AddEntry(h_UH_5,"T5qqqq")
h_UH_1.Draw()
h_UH_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/UH.png")
tl.Clear()

# HT x NJ Overlays
h_VL_2to3_1.SetMaximum(1.1 * max(h_VL_2to3_1.GetMaximum(), h_VL_2to3_5.GetMaximum()) )
h_VL_2to3_1.SetMinimum(0)
h_VL_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_VL_2to3_1,"T1qqqq")
tl.AddEntry(h_VL_2to3_5,"T5qqqq")
h_VL_2to3_1.Draw()
h_VL_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/VL_2to3.png")
tl.Clear()

h_L_2to3_1.SetMaximum(1.1 * max(h_L_2to3_1.GetMaximum(), h_L_2to3_5.GetMaximum()) )
h_L_2to3_1.SetMinimum(0)
h_L_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_L_2to3_1,"T1qqqq")
tl.AddEntry(h_L_2to3_5,"T5qqqq")
h_L_2to3_1.Draw()
h_L_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/L_2to3.png")
tl.Clear()

h_M_2to3_1.SetMaximum(1.1 * max(h_M_2to3_1.GetMaximum(), h_M_2to3_5.GetMaximum()) )
h_M_2to3_1.SetMinimum(0)
h_M_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_M_2to3_1,"T1qqqq")
tl.AddEntry(h_M_2to3_5,"T5qqqq")
h_M_2to3_1.Draw()
h_M_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/M_2to3.png")
tl.Clear()

h_H_2to3_1.SetMaximum(1.1 * max(h_H_2to3_1.GetMaximum(), h_H_2to3_5.GetMaximum()) )
h_H_2to3_1.SetMinimum(0)
h_H_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_H_2to3_1,"T1qqqq")
tl.AddEntry(h_H_2to3_5,"T5qqqq")
h_H_2to3_1.Draw()
h_H_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/H_2to3.png")
tl.Clear()

h_UH_2to3_1.SetMaximum(1.1 * max(h_UH_2to3_1.GetMaximum(), h_UH_2to3_5.GetMaximum()) )
h_UH_2to3_1.SetMinimum(0)
h_UH_2to3_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_UH_2to3_1,"T1qqqq")
tl.AddEntry(h_UH_2to3_5,"T5qqqq")
h_UH_2to3_1.Draw()
h_UH_2to3_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/UH_2to3.png")
tl.Clear()

h_VL_4to6_1.SetMaximum(1.1 * max(h_VL_4to6_1.GetMaximum(), h_VL_4to6_5.GetMaximum()) )
h_VL_4to6_1.SetMinimum(0)
h_VL_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_VL_4to6_1,"T1qqqq")
tl.AddEntry(h_VL_4to6_5,"T5qqqq")
h_VL_4to6_1.Draw()
h_VL_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/VL_4to6.png")
tl.Clear()

h_L_4to6_1.SetMaximum(1.1 * max(h_L_4to6_1.GetMaximum(), h_L_4to6_5.GetMaximum()) )
h_L_4to6_1.SetMinimum(0)
h_L_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_L_4to6_1,"T1qqqq")
tl.AddEntry(h_L_4to6_5,"T5qqqq")
h_L_4to6_1.Draw()
h_L_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/L_4to6.png")
tl.Clear()

h_M_4to6_1.SetMaximum(1.1 * max(h_M_4to6_1.GetMaximum(), h_M_4to6_5.GetMaximum()) )
h_M_4to6_1.SetMinimum(0)
h_M_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_M_4to6_1,"T1qqqq")
tl.AddEntry(h_M_4to6_5,"T5qqqq")
h_M_4to6_1.Draw()
h_M_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/M_4to6.png")
tl.Clear()

h_H_4to6_1.SetMaximum(1.1 * max(h_H_4to6_1.GetMaximum(), h_H_4to6_5.GetMaximum()) )
h_H_4to6_1.SetMinimum(0)
h_H_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_H_4to6_1,"T1qqqq")
tl.AddEntry(h_H_4to6_5,"T5qqqq")
h_H_4to6_1.Draw()
h_H_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/H_4to6.png")
tl.Clear()

h_UH_4to6_1.SetMaximum(1.1 * max(h_UH_4to6_1.GetMaximum(), h_UH_4to6_5.GetMaximum()) )
h_UH_4to6_1.SetMinimum(0)
h_UH_4to6_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_UH_4to6_1,"T1qqqq")
tl.AddEntry(h_UH_4to6_5,"T5qqqq")
h_UH_4to6_1.Draw()
h_UH_4to6_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/UH_4to6.png")
tl.Clear()

h_VL_7plus_1.SetMaximum(1.1 * max(h_VL_7plus_1.GetMaximum(), h_VL_7plus_5.GetMaximum()) )
h_VL_7plus_1.SetMinimum(0)
h_VL_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_VL_7plus_1,"T1qqqq")
tl.AddEntry(h_VL_7plus_5,"T5qqqq")
h_VL_7plus_1.Draw()
h_VL_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/VL_7plus.png")
tl.Clear()

h_L_7plus_1.SetMaximum(1.1 * max(h_L_7plus_1.GetMaximum(), h_L_7plus_5.GetMaximum()) )
h_L_7plus_1.SetMinimum(0)
h_L_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_L_7plus_1,"T1qqqq")
tl.AddEntry(h_L_7plus_5,"T5qqqq")
h_L_7plus_1.Draw()
h_L_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/L_7plus.png")
tl.Clear()

h_M_7plus_1.SetMaximum(1.1 * max(h_M_7plus_1.GetMaximum(), h_M_7plus_5.GetMaximum()) )
h_M_7plus_1.SetMinimum(0)
h_M_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_M_7plus_1,"T1qqqq")
tl.AddEntry(h_M_7plus_5,"T5qqqq")
h_M_7plus_1.Draw()
h_M_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/M_7plus.png")
tl.Clear()

h_H_7plus_1.SetMaximum(1.1 * max(h_H_7plus_1.GetMaximum(), h_H_7plus_5.GetMaximum()) )
h_H_7plus_1.SetMinimum(0)
h_H_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_H_7plus_1,"T1qqqq")
tl.AddEntry(h_H_7plus_5,"T5qqqq")
h_H_7plus_1.Draw()
h_H_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/H_7plus.png")
tl.Clear()

h_UH_7plus_1.SetMaximum(1.1 * max(h_UH_7plus_1.GetMaximum(), h_UH_7plus_5.GetMaximum()) )
h_UH_7plus_1.SetMinimum(0)
h_UH_7plus_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_UH_7plus_1,"T1qqqq")
tl.AddEntry(h_UH_7plus_5,"T5qqqq")
h_UH_7plus_1.Draw()
h_UH_7plus_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/UH_7plus.png")
tl.Clear()

# Inclusive
h_inc_1 = h_2to3_1.Clone()
h_inc_1.SetTitle("Inclusive")
h_inc_1.Add(h_4to6_1)
h_inc_1.Add(h_7plus_1)
h_inc_5 = h_2to3_5.Clone()
h_inc_5.Add(h_4to6_5)
h_inc_5.Add(h_7plus_5)
h_inc_1.SetMaximum(1.3*max(h_inc_1.GetMaximum(),h_inc_5.GetMaximum()))
h_inc_1.SetMinimum(0)
h_inc_1.SetLineColor(ROOT.kRed)
tl.AddEntry(h_inc_1,"T1qqqq")
tl.AddEntry(h_inc_5,"T5qqqq")
h_inc_1.Draw()
h_inc_5.Draw("same")
tl.Draw()
canvas.SaveAs("pngs/inc.png")
